### ISSUE TITLE
framework.exception.ApiDefault when clicking the Save button.

### ISSUE THREAD

**Issue by douglascrp** [EisenVault/ev-outlook-plugin-github#1]
Hello.

We were playing with the addon in a Outlook 2013, running on Windows 10.

When we clicked the save button after selecting the destination folder, the error message **framework.exception.ApiDefault** appears, and nothing happens.

![imagem](https://user-images.githubusercontent.com/5930258/27963422-630a4320-630b-11e7-80f7-a02773046e7a.png)

How can I help solve this problem?
Is there any log file the addon creates that I can check?

**EDIT:** While I was getting the information to post here, I think I found out what really caused the problem.

It seems the email's subject contained a space at the end of if it.

This is what I got from the Alfresco's log:

`2017-07-07 15:59:44,272 ERROR [org.alfresco.repo.node.integrity.IntegrityChecker] [http-nio-8080-exec-21] Found 1 integrity violations:
Invalid property value:
   Node: workspace://SpacesStore/3a86294a-b9d2-4bb6-9b6a-b86db11795bf
   Name: RESe SENHA DE USUARIO
   Type: {http://www.alfresco.org/model/content/1.0}folder
   Property: {http://www.alfresco.org/model/content/1.0}name
   Constraint: 06070123 Value 'RESe SENHA DE USUARIO ' is not valid as a file name. This property must be a valid file name.`

So I guess that putting some cleaning logic for the node name can do the trick.
In this specifc case, a trim should be enough.

**Comment by vipulswarup** [comment]
Thanks for raising this, Douglas. We will get this fixed. Please do raise any other bugs you encounter.

**Comment by douglascrp** [comment]
Sure... you can count on me for that.
Thank you for the project.

**Comment by vipulswarup** [comment]
We have fixed this in version 1.0.14 of the plugin. Please download latest and try again. Closing this issue for now.

**Comment by douglascrp** [comment]
It works now.
Thank you
