### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by douglascrp** [EisenVault/ev-outlook-plugin-github#2]
May you tell me what are the files I have to change in order to get it translated into Brazilian Portuguese?

**Comment by vipulswarup** [comment]
Currently all strings are hard-coded unfortunately. If you end up creating a Portuguese version, using a properties file, please do share the code.

**Comment by douglascrp** [comment]
Yes, of course.
I am already trying to understand it, and I will let you know how it goes.

**Comment by vipulswarup** [comment]
Thanks Douglas - I will close this issue for now. Looking forward to hearing about your progress.
