### ISSUE TITLE
It doesn't work with Alfresco servers using HTTPs and self-signed certificates

### ISSUE THREAD

**Issue by angelborroy-ks** [EisenVault/ev-outlook-plugin-github#4]
I've tested with different servers, but for instance I'm including public "my.alfresco.com" configuration:
![image](https://user-images.githubusercontent.com/5584952/32545667-bdcd8af6-c47c-11e7-8270-6c28c15a2060.png)

**Comment by vipulswarup** [comment]
Hi Angel - not sure why this is happening. Is the server running Alfresco Community 5.2? I will separately email you some test credentials as well (request you to send me an email at contact _at_ eisenvault.com).

**Comment by angelborroy-ks** [comment]
I've tested with 2 different servers running 201707 and HTTPs with self-signed SSL certificates. 
The image I've attached above is from "my.alfresco.com", which is using Alfresco 5.2.1 and providing a trusted SSL certificate.
Is there any place where I can find logs for EV Outlook plugin?

**Comment by vipulswarup** [comment]
I don't think logging is enabled. If you can send some sample login information for a web-facing server, I can get our developer to take a look and also to start generating logs somewhere.

**Comment by angelborroy-ks** [comment]
I don't have currently any web-facing server, but you can create a user at https://my.alfresco.com to test (it's free). You can also send me a verbose version of the addon and I can share my tests with you.
Thanks for your quick response!

**Comment by vipulswarup** [comment]
Log has this error: 08-11-2017 17:04:44 : method:POST, module: https://my.alfresco.com/alfresco/api/-default-/public/authentication/versions/1/tickets, url: https://my.alfresco.com/alfresco/api/-default-/public/authentication/versions/1/tickets, status: Response Exception with status code : ServiceUnavailable

Log seems to be available at: 
%appdata%/EisenVaultOutlook_plugin/log/

**Comment by vipulswarup** [comment]
![image](https://user-images.githubusercontent.com/10922882/32547581-e7a08618-c4a8-11e7-91f3-23b71b343dbc.png)

That's the error when calling the API from Postman (calling https://my.alfresco.com/alfresco/api/-default-/public/authentication/versions/1/tickets )

**Comment by angelborroy-ks** [comment]
I have more ore less the same errors in the log files. From that, I can see that:

* The addon does not work with my.alfresco.com as Alfresco is using a customised version for the web
* The addon does not work with SSL self-signed certificates with Alfresco 201707

Probably the problem is at this point: https://github.com/EisenVault/ev-outlook-plugin-github/blob/master/EisenVaultOutlookPlugin.Data/API.cs#L60

It looks like there is not SSL handling in HttpClient.

I've seen some people answering at StackOverflow (https://stackoverflow.com/questions/12553277/allowing-untrusted-ssl-certificates-with-httpclient) but probably this requires further analysis.

**Comment by vipulswarup** [comment]
Thanks Angel - we will try to fix this. If in the meanwhile you come up with a solution, do submit it here. It does work with regular trusted SSL certificates (eg. it does work with https://www.eisenvault.net)

**Comment by angelborroy-ks** [comment]
Probably this feature has not to be supported by the plugin. Just tell the people to use a trusted SSL certificate is enough.

**Comment by angelborroy-ks** [comment]
I've added following line before `HttpClient` invocations and it's working with self-signed certificates:

`System.Net.ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`

Anyway this is not a real solution, it's just a dirty workaround.
